INSERT INTO users (email, password, type) VALUES
('calgaryjains@gmail.com', '1234', 'EC'),
('president.jsoc@gmail.com', '1234', 'EC'),
('vicepresident.jsoc@gmail.com', '1234', 'EC'),
('treasurer@gmail.com', '1234', 'EC'),
('events.jsoc@gmail.com', '1234', 'DIR'),
('operations.jsoc@gmail.com', '1234', 'DIR'),
('fundraising.jsoc@gmail.com', '1234', 'DIR'),
('newidea.jsoc@gmail.com', '1234', 'DIR'),
('webcomm.jsoc@gmail.com', '1234', 'DIR'),
('pathshala@gmail.com', '1234', 'DIR'),
('rahul.shial@gmail.com', '1234', 'MEM'),